import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const moduleSource = readFileSync(new URL("../public/views/bulk-json-add.js", import.meta.url), "utf8");
const appSource = readFileSync(new URL("../public/app.js", import.meta.url), "utf8");
const cssSource = readFileSync(new URL("../public/styles/bulk-json-add.css", import.meta.url), "utf8");

test("JSON一括追加はタイトル一括追加と別入口で最大10作品を扱う", () => {
  assert.match(moduleSource, /const MAX_JSON_WORKS = 10/);
  assert.match(moduleSource, /open-bulk-json-add/);
  assert.match(moduleSource, /タイトルで追加/);
  assert.match(moduleSource, /JSONで追加/);
  assert.match(moduleSource, /JSONでまとめて追加/);
});

test("配列・works配列・items配列・単一作品のJSONを受け付ける", () => {
  assert.match(moduleSource, /if \(Array\.isArray\(parsed\)\)/);
  assert.match(moduleSource, /Array\.isArray\(parsed\.works\)/);
  assert.match(moduleSource, /Array\.isArray\(parsed\.items\)/);
  assert.match(moduleSource, /typeof parsed\.title === "string"/);
  assert.match(moduleSource, /stripCodeFence/);
});

test("バックアップJSONの体験とメモをwork_idで作品へ結び直す", () => {
  assert.match(moduleSource, /container\.experiences\.filter/);
  assert.match(moduleSource, /container\.notes\.filter/);
  assert.match(moduleSource, /experienceMap\.set/);
  assert.match(moduleSource, /payload\.experience_id = mapped/);
  assert.match(moduleSource, /autoGeneratedMemoNote/);
});

test("ID・日時・公開範囲は作品作成payloadへ渡さない", () => {
  assert.match(moduleSource, /ID・所有者・作成日時・公開範囲は引き継がず/);
  assert.doesNotMatch(moduleSource, /payload\s*=\s*\{[^}]*owner_id/s);
  assert.doesNotMatch(moduleSource, /payload\s*=\s*\{[^}]*created_at/s);
  assert.doesNotMatch(moduleSource, /payload\s*=\s*\{[^}]*visibility/s);
});

test("作品・分類・数値・メモを事前検証し同名作品を初期状態で除外する", () => {
  assert.match(moduleSource, /WORK_TYPES/);
  assert.match(moduleSource, /WORK_STATUSES/);
  assert.match(moduleSource, /labelsValue/);
  assert.match(moduleSource, /metadataValue/);
  assert.match(moduleSource, /progress_currentがprogress_totalを超えています/);
  assert.match(moduleSource, /alreadyExists/);
  assert.match(moduleSource, /allow_duplicates/);
});

test("既存APIを順番に使い、体験追加後は元の作品状態を復元する", () => {
  assert.match(moduleSource, /api\("\/api\/works"/);
  assert.match(moduleSource, /\/experiences`/);
  assert.match(moduleSource, /\/notes`/);
  assert.match(moduleSource, /restoreWorkFields/);
  assert.match(moduleSource, /method: "PATCH"/);
  assert.match(moduleSource, /追加中 \$\{candidateIndex \+ 1\} \/ \$\{analysis\.candidates\.length\}/);
});

test("作品本体の失敗だけを再試行JSONに残し、補足失敗は別レポートにする", () => {
  assert.match(moduleSource, /workFailures\.map\(\(\{ item \}\) => item\.retryValue\)/);
  assert.match(moduleSource, /再試行用JSONだけを入力欄に残しました/);
  assert.match(moduleSource, /bulkJsonFailureReport/);
  assert.match(moduleSource, /失敗内容をコピー/);
});

test("JSONファイル選択・ひな形コピー・下書き保持を備える", () => {
  assert.match(moduleSource, /MAX_JSON_FILE_BYTES/);
  assert.match(moduleSource, /file\.text\(\)/);
  assert.match(moduleSource, /templateJson/);
  assert.match(moduleSource, /navigator\.clipboard\.writeText/);
  assert.match(moduleSource, /sakuhin-log-bulk-json-draft-v1/);
});

test("アプリ起動とCtrlまたはCmd+Enterへ接続する", () => {
  assert.match(appSource, /import \{ initBulkJsonAdd \} from "\.\/views\/bulk-json-add\.js"/);
  assert.match(appSource, /initBulkJsonAdd\(\)/);
  assert.match(appSource, /"bulkJsonAddForm"/);
});

test("進捗表示は動きを減らす設定に従い、モバイルでは上部ボタンを隠す", () => {
  assert.match(cssSource, /#bulkJsonProgress i/);
  assert.match(cssSource, /prefers-reduced-motion:reduce/);
  assert.match(cssSource, /bulk-json-top-trigger\{display:none\}/);
});
